include: package:very_good_analysis/analysis_options.5.1.0.yaml

analyzer: 
  errors:
    inference_failure_on_function_invocation: ignore
linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
    lines_longer_than_80_chars: false