name: client
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cached_network_image: ^3.3.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_form_builder: ^9.1.1
  flutter_secure_storage: ^9.0.0
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^12.1.0
  intl: ^0.18.0

  # hwdb packages
  cacher:
    path: packages/cacher
  client_auth:
    path: packages/client_auth
  client_repositories:
    path: packages/client_repositories
  core_components:
    path: packages/core_components  
  general_utilities:
    path: ../shared-packages/general_utilities
  hwdb_models:
    path: ../shared-packages/hwdb_models
  requester:
    path: packages/requester

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/sample.png
    - assets/hw-dashboard-logo.png
    - assets/homepage-background.png
    - assets/courses-page-background.png
