name: cacher
description: HW Dashboard local caching utility.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.1

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
