name: client_model_validators
description: Model Validators for HW Dashboard Client
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies: 
  client_repositories:
    path: ../client_repositories
  general_utilities:
    path: ../../../shared-packages/general_utilities
  hwdb_models:
    path: ../../../shared-packages/hwdb_models

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
